/* AUTO-GENERATED by scripts/gen_jni_bridge.py — DO NOT EDIT（P3）。
 * 由 Java native 声明生成：改 Java 签名后请重新生成，勿手改符号名。
 *   生成: python3 scripts/gen_jni_bridge.py --java <java目录> --bridge <输出.c>
 */
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "vua.h"

/* .vus 编译成的入口（generator 已把 main 改名 vus_main 以避免与 Android 冲突） */
extern int vus_main(void);

/* 缓存 JavaVM，供重绘回调（可能非 Java 线程）Attach 使用。在 JNI_OnLoad 里存。 */
static JavaVM *g_vm = NULL;
/* VuaBridge 类的全局引用 + 静态方法 id，避免每次回调都 FindClass。 */
static jclass     g_VuaBridge = NULL;
static jmethodID  g_onNativeRerender = NULL;
static jmethodID  g_callJava = NULL;

/* 平台能力桥分发（定义见下）：VUS 内建 → VuaBridge.callJava（Java 暴露网络/文件能力）。 */
static void java_rpc_dispatch(const char *api, const char *args, char **out);

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
    (void)reserved;
    g_vm = vm;
    JNIEnv *env = NULL;
    if ((*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) return JNI_VERSION_1_6;
    jclass local = (*env)->FindClass(env, "com/vus/android/VuaBridge");
    if (!local) return JNI_VERSION_1_6;
    g_VuaBridge = (*env)->NewGlobalRef(env, local);
    (*env)->DeleteLocalRef(env, local);
    if (g_VuaBridge) {
        g_onNativeRerender = (*env)->GetStaticMethodID(env, g_VuaBridge, "onNativeRerender", "()V");
        g_callJava = (*env)->GetStaticMethodID(env, g_VuaBridge, "callJava",
                                               "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
        /* 平台能力桥：网络/文件由 Java 暴露、VUS 调用（桌面/纯 native 未注册时内建回退） */
        vus_set_java_callback(java_rpc_dispatch);
    }
    return JNI_VERSION_1_6;
}


/* ---- 平台能力桥分发（native → Java 同步 RPC） --------------------------------
 * VUS 内建（网络_GET/文件_读取 等）→ vus_java_rpc → 本函数 → VuaBridge.callJava →
 * JSON 结果原样回传。Java 侧保证不抛异常（错误转 ok:0）。 */
static void java_rpc_dispatch(const char *api, const char *args, char **out) {
    *out = NULL;
    if (!g_vm || !g_VuaBridge || !g_callJava || !api || !args) return;
    JNIEnv *env = NULL;
    jint st = (*g_vm)->GetEnv(g_vm, (void **)&env, JNI_VERSION_1_6);
    int attached = 0;
    if (st != JNI_OK) {
        if ((*g_vm)->AttachCurrentThread(g_vm, &env, NULL) != JNI_OK) return;
        attached = 1;
    }
    jstring jap = (*env)->NewStringUTF(env, api);
    jstring jars = (*env)->NewStringUTF(env, args);
    jstring jres = (jstring)(*env)->CallStaticObjectMethod(env, g_VuaBridge, g_callJava, jap, jars);
    (*env)->DeleteLocalRef(env, jap);
    (*env)->DeleteLocalRef(env, jars);
    if (jres) {
        const char *c = (*env)->GetStringUTFChars(env, jres, 0);
        if (c) { *out = strdup(c); (*env)->ReleaseStringUTFChars(env, jres, c); }
        (*env)->DeleteLocalRef(env, jres);
    }
    /* Java 异常（理论上 callJava 内部已捕获）：清空避免污染后续 JNI 调用 */
    if ((*env)->ExceptionCheck(env)) (*env)->ExceptionClear(env);
    if (attached) (*g_vm)->DetachCurrentThread(g_vm);
}


/* ---- 重绘回调（native → Java） ----------------------------------------- */
/* 屏栈变化（界面_显示/返回/返回至）后由 vua 调用，回 Java 触发 View 重建。 */
static void native_rerender_cb(VuaSession *session, void *ud) {
    (void)session; (void)ud;
    if (!g_vm || !g_onNativeRerender) return;
    JNIEnv *env = NULL;
    int attached = 0;
    if ((*g_vm)->GetEnv(g_vm, (void **)&env, JNI_VERSION_1_6) != JNI_OK) {
        if ((*g_vm)->AttachCurrentThread(g_vm, &env, NULL) != JNI_OK) return;
        attached = 1;
    }
    (*env)->CallStaticVoidMethod(env, g_VuaBridge, g_onNativeRerender);
    if (attached) (*g_vm)->DetachCurrentThread(g_vm);
}


/* ---- 事件触发共用（按 事件名 / 控件 id 派发） ---- */
static int do_trigger(JNIEnv *env, jstring event_or_id, jstring vars_json, int by_id) {
    VuaSession *s = vua_global_session(NULL);
    VuaScreen *cur = s ? vua_session_current(s) : NULL;
    if (!cur) return -1;

    const char *ev = event_or_id ? (*env)->GetStringUTFChars(env, event_or_id, 0) : NULL;
    const char *vars = vars_json ? (*env)->GetStringUTFChars(env, vars_json, 0) : NULL;

    VuaError err = {0};
    VusDict *dict = (vars && vars[0]) ? vua_dict_from_json(vars, &err) : NULL;

    if (by_id) vua_trigger_by_id(cur, ev ? ev : "", dict);
    else       vua_trigger_event(cur, ev ? ev : "", dict);

    if (dict) vus_unref((void *)dict);
    if (ev) (*env)->ReleaseStringUTFChars(env, event_or_id, ev);
    if (vars) (*env)->ReleaseStringUTFChars(env, vars_json, vars);
    return 0;
}

/* ---- vuaInit ------------------------------------------------------- */
JNIEXPORT jint JNICALL
Java_com_vus_android_VuaBridge_vuaInit(JNIEnv *env, jclass clazz) {
    (void)env; (void)clazz;

    VuaError err = {0};
    VuaSession *s = vua_global_session(&err);
    if (!s) { fprintf(stderr, "[vua] vuaInit: %s\n", err.msg); return -1; }
    /* 预加载控件表（已由 vuaSetRootDir 切到文件目录，用相对路径读）。失败不致命。 */
    {
        FILE *cf = fopen("vua_controls.json", "rb");
        if (cf) {
            fseek(cf, 0, SEEK_END); long l = ftell(cf); fseek(cf, 0, SEEK_SET);
            if (l > 0) {
                char *buf = (char *)malloc((size_t)l + 1);
                if (buf) {
                    size_t n = fread(buf, 1, (size_t)l, cf);
                    buf[n] = '\0';
                    if (vua_control_table_load(buf, NULL) != 0)
                        fprintf(stderr, "[vua] 控件表加载失败\n");
                    free(buf);
                }
            }
            fclose(cf);
        } else {
            fprintf(stderr, "[vua] 未找到 vua_controls.json\n");
        }
    }
    /* 注册重绘钩子：vus_main 里 界面_显示/返回 换屏时，回 Java 重建 View。 */
    vua_session_set_rerender_hook(s, native_rerender_cb, NULL);
    int rc = vus_main();
    return rc == 0 ? 0 : -2;

}

/* ---- vuaRenderTreeBytes ------------------------------------------------------- */
JNIEXPORT jbyteArray JNICALL
Java_com_vus_android_VuaBridge_vuaRenderTreeBytes(JNIEnv *env, jclass clazz) {
    (void)env; (void)clazz;

    VuaSession *s = vua_global_session(NULL);
    VuaScreen *cur = s ? vua_session_current(s) : NULL;
    if (!cur) return NULL;
    const char *tree = vua_screen_dump_rendertree(cur);
    if (!tree) return NULL;
    jsize len = (jsize)strlen(tree);
    jbyteArray arr = (*env)->NewByteArray(env, len);
    if (!arr) return NULL;
    (*env)->SetByteArrayRegion(env, arr, 0, len, (const jbyte *)tree);
    return arr;

}

/* ---- vuaRenderHash ------------------------------------------------------- */
JNIEXPORT jlong JNICALL
Java_com_vus_android_VuaBridge_vuaRenderHash(JNIEnv *env, jclass clazz) {
    (void)env; (void)clazz;

    VuaSession *s = vua_global_session(NULL);
    VuaScreen *cur = s ? vua_session_current(s) : NULL;
    if (!cur) return -1;
    return (jlong)(vua_screen_rendertree_hash(cur) & 0x7FFFFFFFFFFFFFFFULL);

}

/* ---- vuaScreenId ------------------------------------------------------- */
JNIEXPORT jlong JNICALL
Java_com_vus_android_VuaBridge_vuaScreenId(JNIEnv *env, jclass clazz) {
    (void)env; (void)clazz;

    VuaSession *s = vua_global_session(NULL);
    VuaScreen *cur = s ? vua_session_current(s) : NULL;
    if (!cur) return -1;
    return (jlong)vua_screen_seq(cur);

}

/* ---- vuaSetRootDir ------------------------------------------------------- */
JNIEXPORT void JNICALL
Java_com_vus_android_VuaBridge_vuaSetRootDir(JNIEnv *env, jclass clazz, jstring filesDir) {

    if (!filesDir) return;
    const char *d = (*env)->GetStringUTFChars(env, filesDir, 0);
    if (d) { chdir(d); (*env)->ReleaseStringUTFChars(env, filesDir, d); }

}

/* ---- vuaTrigger ------------------------------------------------------- */
JNIEXPORT jint JNICALL
Java_com_vus_android_VuaBridge_vuaTrigger(JNIEnv *env, jclass clazz, jstring eventName, jstring varsJson) {

    return do_trigger(env, event_name, vars_json, 0);

}

/* ---- vuaTriggerById ------------------------------------------------------- */
JNIEXPORT jint JNICALL
Java_com_vus_android_VuaBridge_vuaTriggerById(JNIEnv *env, jclass clazz, jstring nodeId, jstring varsJson) {

    return do_trigger(env, node_id, vars_json, 1);

}

