// 由 src/lsp/vus_builtin.c 自动生成，请勿手改。
// 补全/详情展示使用 name/signature/description/example/kind。
export const VUS_BUILTINS = [
  {"name": "图形_初始化", "signature": "图形_初始化(宽, 高, 标题)", "description": "初始化图形窗口。必须最先调用，宽高为窗口像素尺寸，标题为窗口标题字符串。", "example": "图形_初始化(320, 240, \"示例\")\n图形_刷新()\n图形_保持()", "kind": "graphic"},
  {"name": "图形_画点", "signature": "图形_画点(x, y, 颜色)", "description": "在坐标 (x, y) 处绘制一个像素点。颜色为 0xRRGGBB 形式的整数。", "example": "图形_画点(160, 120, 0xFF0000)", "kind": "graphic"},
  {"name": "图形_画线", "signature": "图形_画线(x1, y1, x2, y2, 颜色[, 线宽, 虚线, 箭头])", "description": "从 (x1,y1) 到 (x2,y2) 绘制一条线段。可选参数：线宽(默认1)、虚线(默认0)、箭头(默认0)。", "example": "图形_画线(0, 0, 100, 50, 0xFF0000, 3, 0, 1)", "kind": "graphic"},
  {"name": "图形_矩形", "signature": "图形_矩形(x, y, 宽, 高, 颜色)", "description": "在 (x,y) 处绘制一个矩形的外框。颜色为 0xRRGGBB。", "example": "图形_矩形(10, 10, 100, 60, 0x00FF00)", "kind": "graphic"},
  {"name": "图形_填充", "signature": "图形_填充(x, y, 宽, 高, 颜色)", "description": "在 (x,y) 处绘制一个填充的实心矩形区域。颜色为 0xRRGGBB。", "example": "图形_填充(10, 10, 100, 60, 0x0000FF)", "kind": "graphic"},
  {"name": "图形_文字", "signature": "图形_文字(x, y, 文本, 颜色)", "description": "在 (x,y) 处绘制一行文字。文本为字符串，颜色为 0xRRGGBB。", "example": "图形_文字(10, 20, \"你好\", 0xFFFFFF)", "kind": "graphic"},
  {"name": "图形_刷新", "signature": "图形_刷新()", "description": "将帧缓冲内容上屏重绘，让已绘制的图形显示出来。", "example": "图形_矩形(10, 10, 100, 60, 0x00FF00)\n图形_刷新()", "kind": "graphic"},
  {"name": "图形_保持", "signature": "图形_保持()", "description": "进入消息循环并保持窗口打开，直到用户关闭窗口。通常放在脚本末尾。", "example": "图形_初始化(320, 240, \"示例\")\n图形_保持()", "kind": "graphic"},
  {"name": "图形_MD", "signature": "图形_MD(x, y, 宽度, 文本)", "description": "以最小 Markdown 子集渲染文本（标题/列表/引用/代码块/分隔线），按宽度折行，返回占用行数。", "example": "行数 = 图形_MD(5, 5, 300, \"# 标题\n- 项1\n- 项2\")", "kind": "graphic"},
  {"name": "图形_滚动容器", "signature": "图形_滚动容器(名, x, y, 宽, 高, 内容高)", "description": "登记一个滚动容器：指定可视区域 (x,y,宽,高) 与内容总高度，容器内绘制自动按偏移裁剪平移。", "example": "图形_滚动容器(\"列表\", 0, 20, 300, 100, 300)", "kind": "graphic"},
  {"name": "图形_滚动容器滚", "signature": "图形_滚动容器滚(名, dy)", "description": "将指定滚动容器的当前偏移增减 dy（dy<0 向下内容滚动），返回新的偏移值。", "example": "图形_滚动容器滚(\"列表\", 10)", "kind": "graphic"},
  {"name": "图形_滚动容器偏移", "signature": "图形_滚动容器偏移(名)", "description": "读取指定滚动容器当前的滚动偏移量。", "example": "偏移 = 图形_滚动容器偏移(\"列表\")", "kind": "graphic"},
  {"name": "图形_背景图", "signature": "图形_背景图(x, y, 宽, 高, PNG路径)", "description": "解码一张 PNG 图片并拉伸铺满指定区域，作为控件或页面背景。路径为图片文件路径字符串。", "example": "图形_背景图(0, 0, 320, 240, \"bg.png\")", "kind": "graphic"},
  {"name": "图形_字体_加载", "signature": "图形_字体_加载(路径, 字号)", "description": "从外部 TTF/OTF 字体文件加载全局活动字体并设置字号。", "example": "图形_字体_加载(\"/sdcard/font.ttf\", 18)", "kind": "graphic"},
  {"name": "图形_字体已加载", "signature": "图形_字体已加载()", "description": "查询外部字体是否已成功加载，返回 \"true\"/\"false\"。", "example": "如果 图形_字体已加载() == \"true\" 则\n    打印(\"字体已加载\")\n结束", "kind": "graphic"},
  {"name": "图形_页面_打开", "signature": "图形_页面_打开(名)", "description": "打开（压栈）指定页面。页面为脚本中约定的函数 `页_<名>()`。", "example": "图形_页面_打开(\"设置\")", "kind": "graphic"},
  {"name": "图形_页面_返回", "signature": "图形_页面_返回()", "description": "从当前页面返回上一级页面（弹栈）。", "example": "图形_页面_返回()", "kind": "graphic"},
  {"name": "图形_页面_当前", "signature": "图形_页面_当前()", "description": "返回当前所在页面的名称字符串。", "example": "当前页 = 图形_页面_当前()", "kind": "graphic"},
  {"name": "图形_页面_绘制", "signature": "图形_页面_绘制()", "description": "重新绘制当前页面的内容，用于页面切换后的刷新。", "example": "图形_页面_绘制()", "kind": "graphic"},
  {"name": "图形_按钮", "signature": "图形_按钮(名, x, y, 宽, 高, 文本)", "description": "创建并绘制一个按钮，同时登记其命中矩形，供 `图形_按钮点击` 检测。", "example": "图形_按钮(\"开始\", 50, 80, 120, 40, \"确定\")", "kind": "graphic"},
  {"name": "图形_取事件", "signature": "图形_取事件()", "description": "非阻塞处理 X 事件队列，刷新点击/按键/鼠标坐标等交互状态。", "example": "循环中调用：图形_取事件()", "kind": "graphic"},
  {"name": "图形_按键", "signature": "图形_按键()", "description": "返回最后一个按键的字符（字符串）。", "example": "按键 = 图形_按键()", "kind": "graphic"},
  {"name": "图形_按键码", "signature": "图形_按键码()", "description": "返回最后一个按键的键码（整数）。", "example": "码 = 图形_按键码()", "kind": "graphic"},
  {"name": "图形_鼠标位置", "signature": "图形_鼠标位置()", "description": "返回鼠标当前位置坐标，通常为 \"x,y\" 形式的字符串。", "example": "位置 = 图形_鼠标位置()", "kind": "graphic"},
  {"name": "图形_鼠标x", "signature": "图形_鼠标x()", "description": "返回鼠标当前的 X 坐标（整数）。", "example": "x = 图形_鼠标x()", "kind": "graphic"},
  {"name": "图形_鼠标y", "signature": "图形_鼠标y()", "description": "返回鼠标当前的 Y 坐标（整数）。", "example": "y = 图形_鼠标y()", "kind": "graphic"},
  {"name": "图形_滚轮", "signature": "图形_滚轮()", "description": "返回滚轮的滚动量，配合滚动容器使用。", "example": "dy = 图形_滚轮()", "kind": "graphic"},
  {"name": "图形_键按下", "signature": "图形_键按下(键)", "description": "检测指定键是否被按下，返回 \"true\"/\"false\"。键名为键的字符或键名。", "example": "如果 图形_键按下(\"a\") == \"true\" 则\n    打印(\"A 被按下\")\n结束", "kind": "graphic"},
  {"name": "图形_悬停", "signature": "图形_悬停(名)", "description": "检测鼠标是否悬停在指定控件上，返回 \"true\"/\"false\"。", "example": "如果 图形_悬停(\"按钮\") == \"true\" 则 ... 结束", "kind": "graphic"},
  {"name": "图形_主题", "signature": "图形_主题(背景, 边框, 高亮, 正文, 文字)", "description": "设置全局主题色。五个参数分别为：背景、边框、高亮、正文、文字颜色（0xRRGGBB），均可省略。", "example": "图形_主题(0x202020, 0x606060, 0x409FFF, 0xFFFFFF, 0xFFFFFF)", "kind": "graphic"},
  {"name": "图形_卡片", "signature": "图形_卡片(名, x, y, 宽, 高, 标题)", "description": "绘制一张卡片容器，附带标题文字。", "example": "图形_卡片(\"card1\", 10, 20, 200, 120, \"设置\")", "kind": "graphic"},
  {"name": "图形_面板", "signature": "图形_面板(名, x, y, 宽, 高, 标题)", "description": "绘制一个面板容器，附带标题文字。", "example": "图形_面板(\"panel1\", 10, 20, 200, 120, \"面板\")", "kind": "graphic"},
  {"name": "图形_表单行", "signature": "图形_表单行(名, 标签, x, y, 宽, 文本)", "description": "绘制表单的一行：左侧标签、中间输入框、右侧文本。", "example": "图形_表单行(\"行1\", \"用户名\", 10, 50, 200, \"admin\")", "kind": "graphic"},
  {"name": "图形_行点击", "signature": "图形_行点击(名)", "description": "检测某一行是否被点击，返回 \"true\"/\"false\"。", "example": "如果 图形_行点击(\"行1\") == \"true\" 则 ... 结束", "kind": "graphic"},
  {"name": "图形_圆环", "signature": "图形_圆环(名, x, y, 半径, 比例[, 颜色])", "description": "绘制一个圆环进度条，比例 0~100 表示填充百分比，颜色可省略。", "example": "图形_圆环(\"环1\", 160, 120, 40, 65, 0x409FFF)", "kind": "graphic"},
  {"name": "图形_按钮点击", "signature": "图形_按钮点击(名)", "description": "命中检测指定按钮是否被点击，返回 \"true\"/\"false\"，可直接作为 `如果` 条件。", "example": "如果 图形_按钮点击(\"开始\") == \"true\" 则\n    打印(\"点击了开始\")\n结束", "kind": "graphic"},
  {"name": "图形_模拟点击", "signature": "图形_模拟点击(x, y)", "description": "注入一次点击坐标，用于 headless 环境下的按钮命中路径测试。", "example": "图形_模拟点击(100, 80)", "kind": "graphic"},
  {"name": "图形_标签", "signature": "图形_标签(名, x, y, 文本, 颜色)", "description": "绘制一个静态文本标签控件，可附带颜色。", "example": "图形_标签(\"标题\", 10, 10, \"Hello\", 0xFFFFFF)", "kind": "graphic"},
  {"name": "图形_文本框", "signature": "图形_文本框(名, x, y, 宽, 高, 文本)", "description": "绘制一个文本框控件，可显示用户输入内容。", "example": "图形_文本框(\"输入框\", 10, 60, 200, 30, \"\" )", "kind": "graphic"},
  {"name": "图形_复选框", "signature": "图形_复选框(名, x, y, 文本, 选中)", "description": "绘制一个复选框控件，选中为 1 表示勾选状态。", "example": "图形_复选框(\"记住\", 10, 90, \"记住密码\", 1)", "kind": "graphic"},
  {"name": "图形_进度", "signature": "图形_进度(名, x, y, 宽, 高, 值)", "description": "绘制一个进度条，值为 0~100 表示进度百分比。", "example": "图形_进度(\"进度1\", 10, 120, 200, 16, 45)", "kind": "graphic"},
  {"name": "图形_列表", "signature": "图形_列表(名, x, y, 宽, 高, 行高)", "description": "创建并绘制一个列表容器，之后用 `图形_列表行` 填充行。", "example": "图形_列表(\"列表\", 10, 10, 200, 200, 30)", "kind": "graphic"},
  {"name": "图形_列表行", "signature": "图形_列表行(名, 行, 文本)", "description": "向指定列表添加一行内容（行号从 0 开始）。", "example": "图形_列表行(\"列表\", 0, \"第一项\")\n图形_列表行(\"列表\", 1, \"第二项\")", "kind": "graphic"},
  {"name": "图形_列表选中", "signature": "图形_列表选中(名)", "description": "返回列表中当前选中行的行号（整数）。", "example": "选中行 = 图形_列表选中(\"列表\")", "kind": "graphic"},
  {"name": "图形_列表行点击", "signature": "图形_列表行点击(名, 行)", "description": "检测列表指定行是否被点击，返回 \"true\"/\"false\"。", "example": "如果 图形_列表行点击(\"列表\", 0) == \"true\" 则 ... 结束", "kind": "graphic"},
  {"name": "图形_画布", "signature": "图形_画布(名, x, y, 宽, 高)", "description": "创建一个可独立绘制的逻辑画布区域。", "example": "图形_画布(\"画布1\", 10, 10, 300, 200)", "kind": "graphic"},
  {"name": "图形_画布命中", "signature": "图形_画布命中(名)", "description": "检测指定画布区域内是否发生点击命中，返回 \"true\"/\"false\"。", "example": "如果 图形_画布命中(\"画布1\") == \"true\" 则 ... 结束", "kind": "graphic"},
  {"name": "图形_画布点", "signature": "图形_画布点(名)", "description": "返回画布内点击坐标位置（相对画布原点），通常为 \"x,y\"。", "example": "点 = 图形_画布点(\"画布1\")", "kind": "graphic"},
  {"name": "打印", "signature": "打印(文本)", "description": "将文本输出到控制台并换行；多个参数会拼接打印。", "example": "打印(\"你好，世界\")", "kind": "io"},
  {"name": "输入", "signature": "输入(提示)", "description": "在控制台显示提示并读取一行用户输入，返回该字符串。", "example": "名字 = 输入(\"请输入名字:\")\n打印(\"你好，\" .. 名字)", "kind": "io"},
  {"name": "转数字", "signature": "转数字(值)", "description": "将字符串或数值转为数字类型，供算术运算使用。", "example": "n = 转数字(\"42\")", "kind": "io"},
  {"name": "转文本", "signature": "转文本(值)", "description": "将任意值转为文本字符串，用于拼接与输出。", "example": "文本 = 转文本(3.14)", "kind": "io"},
  {"name": "睡眠", "signature": "睡眠(毫秒)", "description": "让当前线程暂停执行指定毫秒数。", "example": "睡眠(1000)", "kind": "io"},
  {"name": "JSON_解析", "signature": "JSON_解析(文本)", "description": "将 JSON 文本解析为可访问的对象（字典/列表/标量）。", "example": "数据 = JSON_解析(\"{\\\"name\\\":\\\"vus\\\"}\")", "kind": "json"},
  {"name": "JSON_生成", "signature": "JSON_生成(值)", "description": "将 VUS 对象（字典/列表）序列化为 JSON 文本字符串。", "example": "文本 = JSON_生成(数据)", "kind": "json"},
  {"name": "JSON_查询", "signature": "JSON_查询(json, 路径)", "description": "在已解析的 JSON 对象中按路径查询字段，返回对应值。路径为 \"a.b[0]\" 形式。", "example": "名字 = JSON_查询(数据, \"name\")", "kind": "json"},
  {"name": "字典_键", "signature": "字典_键(字典)", "description": "返回字典的所有键组成的列表。", "example": "键列表 = 字典_键(数据)", "kind": "json"},
  {"name": "typeof", "signature": "typeof(值)", "description": "返回值的类型名称字符串。", "example": "打印(typeof(42))", "kind": "json"},
  {"name": "日期_现在", "signature": "日期_现在()", "description": "返回当前日期时间的文本表示。", "example": "打印(日期_现在())", "kind": "date"},
  {"name": "日期_时间戳", "signature": "日期_时间戳()", "description": "返回当前 Unix 时间戳（整数）。", "example": "ts = 日期_时间戳()", "kind": "date"},
  {"name": "日期_年", "signature": "日期_年()", "description": "返回当前年份（整数）。", "example": "年 = 日期_年()", "kind": "date"},
  {"name": "日期_月", "signature": "日期_月()", "description": "返回当前月份（1~12，整数）。", "example": "月 = 日期_月()", "kind": "date"},
  {"name": "日期_日", "signature": "日期_日()", "description": "返回当前是当月的第几天（整数）。", "example": "日 = 日期_日()", "kind": "date"},
  {"name": "日期_时", "signature": "日期_时()", "description": "返回当前小时（0~23，整数）。", "example": "时 = 日期_时()", "kind": "date"},
  {"name": "日期_分", "signature": "日期_分()", "description": "返回当前分钟（0~59，整数）。", "example": "分 = 日期_分()", "kind": "date"},
  {"name": "日期_秒", "signature": "日期_秒()", "description": "返回当前秒（0~59，整数）。", "example": "秒 = 日期_秒()", "kind": "date"},
  {"name": "日期_格式化", "signature": "日期_格式化(格式)", "description": "按给定的格式字符串格式化当前日期时间，返回格式化后的文本。", "example": "打印(日期_格式化(\"%Y-%m-%d %H:%M:%S\"))", "kind": "date"},
  {"name": "日期_解析", "signature": "日期_解析(文本, 格式)", "description": "按格式解析日期时间文本，返回可用于 `日期_从时间戳` 的时间戳。", "example": "ts = 日期_解析(\"2026-08-17\", \"%Y-%m-%d\")", "kind": "date"},
  {"name": "日期_从时间戳", "signature": "日期_从时间戳(时间戳)", "description": "将 Unix 时间戳转换为可读的日期时间文本。", "example": "打印(日期_从时间戳(1750000000))", "kind": "date"},
];
export const VUS_BUILTIN_COUNT = 69;
